### ISSUE TITLE
Unexpected warning for sp objects

### ISSUE THREAD

**Issue by olivroy** [ropensci/rnaturalearthhires#11]
```r
rnaturalearth::ne_states("India")
#> The `returnclass` argument of `ne_download()` sp as of rnaturalearth 1.0.0.
#> ℹ Please use `sf` objects with {rnaturalearth}, support for Spatial objects (sp)
#> will be removed in a future release of the package.
```

I did not specify returnclass. Need to use `returnclass = "sf"` to silence the warning.

Should rnaturalearthhires return sf objects by default?

**Comment by PMassicotte** [comment]
It should/will return `sf` by default in the next release. I will push the change early next week.

**Comment by PMassicotte** [comment]
Closing since fixed in the latest release.
