### ISSUE TITLE
Can't download lakes data due to link issue in ne_download()?

### ISSUE THREAD

**Issue by landLogic** [ropensci/rnaturalearthhires#3]
I am brand new to rnaturalearth. I finally got the rnaturalearthhires package installed: I think it is the http in the url vs the http**s** url where I can  go and find a zip file of the data: 

**No data:** http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_lakes.zip

**Data available:** https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_lakes.zip

**I used:** 
>lakes110 <- ne_download(scale = 110, type = 'lakes', category = 'physical')
**Result:**
trying URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_lakes.zip'
Error in utils::download.file(file.path(address), zip_file <- tempfile()) : 
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_lakes.zip'
In addition: Warning message:
In utils::download.file(file.path(address), zip_file <- tempfile()) :
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_lakes.zip': HTTP status was '500 Internal Server Error'

I hope I have asked this in the correct place. Thanks for your time.

**Comment by landLogic** [comment]
spudunk in cambec/earth seemed to have the same issue: https://github.com/cambecc/earth/pull/97#issuecomment-537629874

**Comment by andysouth** [comment]
Thanks @landLogic and apologies for delay. There was a problem with the NaturalEarth website a couple of weeks ago that caused downloads to fail. Is it OK for you now ?

**Comment by landLogic** [comment]
@andysouth  Thanks Andy, Yes it is working now! Great fun too. 
Thanks
