### ISSUE TITLE
New repo to install the package?

### ISSUE THREAD

**Issue by paocorrales** [ropensci/rnaturalearthhires#5]
Hi,

I was trying to install the package using the following code:

install.packages("rnaturalearthhires", repos = "http://packages.ropensci.org", type = "source")

and I got an error:

Error in install.packages : error reading from connection

After that, I tried changing the repo URL to the ropensci r-universe and it worked perfectly.  

install.packages("rnaturalearthhires", repos = "https://ropensci.r-universe.dev", type = "source")

I hope this helps others :)

**Comment by abigailgolden** [comment]
this was very helpful, thanks!

**Comment by PMassicotte** [comment]
you can also `remotes::install_github("ropensci/rnaturalearthhires")`.

**Comment by PMassicotte** [comment]
I will add this information into the README. Thank you.
