### ISSUE TITLE
Any plans to make it available on CRAN?

### ISSUE THREAD

**Issue by PMassicotte** [ropensci/rnaturalearthhires#6]
I think that could help with the CRAN checks.

**Comment by mps9506** [comment]
The build size of this package is 21.5Mb. I don't think CRAN will accept it (assuming I understand CRAN policies correctly).

> Packages should be of the minimum necessary size. Reasonable compression should be used for data (not just .rda files) and PDF documentation: CRAN will if necessary pass the latter through qpdf.
As a general rule, neither data nor documentation should exceed 5MB (which covers several books). A CRAN package is not an appropriate way to distribute course notes, and authors will be asked to trim their documentation to a maximum of 5MB.

> Where a large amount of data is required (even after compression), consideration should be given to a separate data-only package which can be updated only rarely (since older versions of packages are archived in perpetuity).

> Similar considerations apply to other forms of “data”, e.g., .jar files.

**Comment by PMassicotte** [comment]
I think you are right. Anyhow, we need to get it updated regularly :)

**Comment by andysouth** [comment]
Yes that was my thought before that such a large package would not be accepted to CRAN. 
Re-reading I wonder whether there might be opportunity to get this data only package accepted ? Is there a need ?

> Where a large amount of data is required (even after compression), consideration should be given to a separate data-only package which can be updated only rarely (since older versions of packages are archived in perpetuity).
